---
title: "sample_code"
author: "rk mclin"
date: "2023-03-26"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(viridis)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

theme_set(theme_minimal() + theme(legend.position = "bottom"))
```


```{r}
Datasbases


#Databases for systematic review

# from aws marketplace
https://www.cochranelibrary.com/
  
https://data.cdc.gov/
  
https://github.com/Emory-HITI/EMBED_Open_Data


```


# great example
```{r}
https://www.nature.com/articles/s41591-020-01192-7#Sec2

https://nda.nih.gov/oai/image-assessments.html

https://github.com/epierson9/pain-disparities


```

research groups
```{r}
https://oir.nih.gov/sigs/health-disparities-interest-group
```


Below is a non-exhaustive list of NIH-supported repositories that offer a wide variety of datasets. Browse the variety of repositories supported and select the link provided in the “Access to Data” column for instructions on accessing data from that repository.

```{r}
https://sharing.nih.gov/accessing-data/accessing-scientific-data

```

